; the linear recursive process
(define (factorial n)
  (if (= n 1)
      1
      (* n (factorial (- n 1)))))

; the linear iteritive Processes
(define (factorial n)
  (fact-iter 1 1 n))

(define (fact-iter product counter max-count)
  (if (> counter max-count)
      product
      (fact-iter (* counter product)
                 (+ counter 1)
                 max-count)))

; Exercise 1.9: Each of the following two procedures defines a method for
; adding two positive integers in terms of the procedures inc, which increments
; its argument by 1, and dec, which decrements its argument by 1.

(define (+ a b)
  (if (= a 0)
      b
      (inc (+ (dec a) b))))

(define (+ a b)
  (if (= a 0)
      b
      (+ (dec a) (inc b))))

; Using the substitution model, illustrate the process generated by each
; procedure in evaluating (+ 4 5). Are these processes iterative or recursive?

; #1
(+ 4 5)
(inc (+ 3 5))
(inc (+ 3 (inc (+ 2 5))))
(inc (+ 3 (inc (+ 2 (inc (+ 1 5))))))
(inc (+ 3 (inc (+ 2 (inc (+ 1 (inc (+ 0 5))))))))
(inc (+ 3 (inc (+ 2 (inc (+ 1 6))))))
(inc (+ 3 (inc (+ 2 7))))
(inc (+ 3 8))
(9)
; This process is recursive.

; #2
(+ 4 5)
(+ 3 6)
(+ 2 7)
(+ 1 8)
(+ 0 9)
(9)
; This process is iterative.
